name: fuji-web

services:
  nginx:
    image: nginx:1.25.3-alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www/html
    - ./../icon:/var/www/html/icon
    restart: always

  php:
    image: php:8.1-fpm
    volumes:
    - .:/var/www/html
    restart: always

  fuji-server:
    image: fuji-ext:latest
    restart: always
